[project]
name = "restack-project"
authors = []
description = "Restack token with built-in airdrop"
telemetry = false
requirements = []

[contracts.restack]
path = "contracts/restack.clar"
clarity_version = 2
epoch = 2.4

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false